const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

// const user_queries = [
//   "I want to buy a red dress",
//   "Show me a black leather jacket",
//   "Looking for casual sneakers",
//   "I need a summer dress",
//   "Where can I find blue jeans",
//   "Find me a pair of running shoes",
//   "I want a stylish blazer",
//   "Show me trendy boots",
//   "Looking for a vintage handbag",
//   "I need a new pair of sunglasses",
//   "I want to buy a white t-shirt",
//   "Show me some formal shoes",
//   "Find me a comfortable hoodie",
//   "I need workout gear for women",
//   "I want to buy a men’s suit",
//   "Show me casual shirts for men",
//   "Looking for a denim jacket",
//   "I need a wool scarf",
//   "Find me trendy accessories",
//   "I want to buy a pair of chinos",
//   "Show me floral print dresses",
//   "Looking for a cute skirt",
//   "I need a warm winter coat",
//   "Find me a stylish hat",
//   "I want to buy a leather belt",
//   "Show me boho style tops",
//   "Looking for statement jewelry",
//   "I need a pair of high heels",
//   "Find me comfy loungewear",
//   "I want to buy a printed sweatshirt",
//   "Show me a chic trench coat",
//   "Looking for a casual dress",
//   "I need activewear for men",
//   "Find me minimalist sneakers",
//   "I want to buy an elegant gown",
//   "Show me party dresses",
//   "Looking for office wear",
//   "I need a graphic t-shirt",
//   "Find me a sporty windbreaker",
//   "I want to buy a pair of leggings",
//   "Show me vintage sneakers",
//   "Looking for a summer hat",
//   "I need a pair of dress shoes",
//   "Find me a statement necklace",
//   "I want to buy a cozy sweater",
//   "Show me athletic shorts",
//   "Looking for a silk scarf",
//   "I need a casual jacket",
//   "Find me skinny jeans",
//   "I want to buy a pair of boots",
//   "Show me a patterned dress",
//   "Looking for trendy joggers",
//   "I need a designer bag",
//   "Find me a classic watch",
//   "I want to buy a suit for a wedding",
//   "Show me party wear for men",
//   "Looking for casual trousers",
//   "I need a beach cover-up",
//   "Find me an athletic cap",
//   "I want to buy a pair of flip-flops",
//   "Show me comfortable sandals",
//   "Looking for a trendy hoodie",
//   "I need vintage-inspired tops",
//   "Find me statement earrings",
//   "I want to buy a crop top",
//   "Show me high waist shorts",
//   "Looking for a peacoat",
//   "I need a versatile vest",
//   "Find me a bohemian maxi dress",
//   "I want to buy a pair of wedges",
//   "Show me slim-fit jeans",
//   "Looking for an oversized sweater",
//   "I need a pair of running tights",
//   "Find me a casual blazer",
//   "I want to buy a pair of cufflinks",
//   "Show me minimalist rings",
//   "Looking for eco-friendly clothing",
//   "I need a graphic hoodie",
//   "Find me athletic sneakers",
//   "I want to buy a party jacket",
//   "Show me dressy skirts",
//   "Looking for comfortable flats",
//   "I need a statement brooch",
//   "Find me winter gloves",
//   "I want to buy a sports bra",
//   "Show me yoga pants",
//   "Looking for a fitness tank top",
//   "I need a pair of track pants",
//   "Find me a designer scarf",
//   "I want to buy a pair of ear studs",
//   "Show me silk pajamas",
//   "Looking for a stylish cardigan",
//   "I need a pair of tapered trousers",
//   "Find me a modern peplum top",
//   "I want to buy a chic jumpsuit",
//   "Show me casual overalls",
//   "Looking for a trendy bomber jacket",
//   "I need a pair of comfortable sneakers",
//   "Find me an elegant cocktail dress",
//   "I want to buy a pair of flats",
//   "Show me graphic leggings",
//   "Looking for a tailored suit",
//   "I need a pair of distressed jeans",
//   "Find me summer sandals",
//   "I want to buy a statement cuff bracelet",
//   "Show me minimalistic necklaces",
//   "Looking for casual flip-flops",
//   "I need a pair of comfy joggers",
//   "Find me a patterned scarf",
//   "I want to buy a trendy beanie",
//   "Show me a classic polo shirt",
//   "Looking for a slim-fit blazer",
//   "I need a lightweight raincoat",
//   "Find me stylish rain boots",
//   "I want to buy a pair of athletic socks",
//   "Show me designer sunglasses",
//   "Looking for a cute bomber jacket",
//   "I need a pair of leather boots",
//   "Find me a cozy cardigan",
//   "I want to buy a pair of embroidered jeans",
//   "Show me a retro windbreaker",
//   "Looking for a colorful maxi dress",
//   "I need a pair of high-performance running shoes",
//   "Find me a sustainable t-shirt",
//   "I want to buy a pair of travel sneakers",
//   "Show me a trendy denim skirt",
//   "Looking for a unique statement hat",
//   "I need a pair of water-resistant sneakers",
//   "Find me a casual button-up shirt",
//   "I want to buy a boho-chic dress",
//   "Show me a funky graphic tee",
//   "Looking for elegant evening wear",
//   "I need a pair of lightweight chinos",
//   "Find me a modern athletic jacket",
//   "I want to buy a pair of cozy sweatpants",
//   "Show me comfortable maternity wear",
//   "Looking for plus size fashion",
//   "I need a pair of trendy cuffed pants",
//   "Find me a unique party outfit",
//   "I want to buy a floral summer dress",
//   "Show me a stylish biker jacket",
//   "Looking for a classic trench coat",
//   "I need a pair of color block sneakers",
//   "Find me a vintage graphic sweatshirt",
//   "I want to buy a pair of sporty sandals",
//   "Show me comfortable business casual attire",
//   "Looking for an edgy leather skirt",
//   "I need a pair of breathable running shoes",
//   "Find me a relaxed-fit t-shirt",
//   "I want to buy a bohemian kimono",
//   "Show me a chic off-shoulder top",
//   "Looking for casual cuffed denim",
//   "I need a pair of loose-fit shorts",
//   "Find me a trendy polo dress",
//   "I want to buy a pair of vintage boots",
//   "Show me a modern knit sweater",
//   "Looking for an urban streetwear look",
//   "I need a pair of athletic headbands",
//   "Find me a cute ruffle top",
//   "I want to buy a statement ankle boot",
//   "Show me a stylish wrap dress",
//   "Looking for comfortable lounge shorts",
//   "I need a pair of sports leggings",
//   "Find me a versatile cardigan",
//   "I want to buy a pair of slim-fit trousers",
//   "Show me a fashionable graphic hoodie",
//   "Looking for retro-inspired sunglasses",
//   "I need a pair of comfortable flats for work",
//   "Find me a trendy utility jacket",
//   "I want to buy a pair of denim overalls",
//   "Show me a classic cashmere sweater",
//   "Looking for a minimalist leather bag",
//   "I need a pair of vintage-inspired sneakers",
//   "Find me a relaxed-fit button-down",
//   "I want to buy a pair of statement earrings",
//   "Show me a chic pleated skirt",
//   "Looking for comfortable cotton shorts",
//   "I need a pair of sleek dress pants",
//   "Find me a sporty compression shirt",
//   "I want to buy a pair of funky patterned socks",
//   "Show me a trendy bucket hat",
//   "Looking for a tailored blazer for work",
//   "I need a pair of stretch-fit jeans",
//   "Find me a classic Breton stripe shirt",
//   "I want to buy a pair of designer loafers",
//   "Show me a minimalist ankle strap",
//   "Looking for stylish over-the-knee boots",
//   "I need a pair of cozy fleece joggers",
//   "Find me a chic structured handbag",
//   "I want to buy a pair of casual espadrilles",
//   "Show me a modern pleated dress",
//   "Looking for a versatile workout top",
//   "I need a pair of elegant dress boots",
//   "Find me a trendy embroidered jacket",
//   "I want to buy a pair of lightweight slip-ons",
//   "Show me comfortable knitwear",
//   "Looking for a modern asymmetric top",
//   "I need a pair of classic loafers",
//   "Find me a stylish sequin dress",
//   "I want to buy a pair of vintage varsity sneakers",
//   "I want to buy a pastel skirt",
//   "Show me eco-friendly hoodies",
//   "Looking for a trendy denim vest",
//   "I need a stylish winter hat",
//   "Find me a pair of vintage sunglasses",
//   "I want to buy a soft cashmere scarf",
//   "Show me modern slip-on sneakers",
//   "Looking for a chic office outfit",
//   "I need a versatile summer hat",
//   "Find me colorful bohemian dresses",
//   "I want to buy a pair of slim-fit chinos",
//   "Show me minimalist casual jackets",
//   "Looking for a statement tote bag",
//   "I need an edgy motorcycle jacket",
//   "Find me comfy athleisure wear",
//   "I want to buy a light linen shirt",
//   "Show me cozy knit cardigans",
//   "Looking for stylish casual shorts",
//   "I need a dressy evening gown",
//   "Find me a modern graphic t-shirt",
//   "I want to buy a designer belt",
//   "Show me trendy workout sneakers",
//   "Looking for a durable backpack",
//   "I need a fashionable summer blazer",
//   "Find me a pair of fitted skirts",
//   "I want to buy a unique printed dress",
//   "Show me edgy urban streetwear",
//   "Looking for a sleek black suit",
//   "I need a vibrant summer dress",
//   "Find me a lightweight athletic jacket",
//   "I want to buy a pair of cargo pants",
//   "Show me creative festival outfits",
//   "Looking for classic Oxford shoes",
//   "I need a pair of stylish loafers",
//   "Find me comfy woolen socks",
//   "I want to buy a high-quality raincoat",
//   "Show me waterproof hiking boots",
//   "Looking for trendy festival accessories",
//   "I need a pair of flexible yoga pants",
//   "Find me a durable running cap",
//   "I want to buy a designer watch",
//   "Show me vintage-inspired belts",
//   "Looking for a modern street style hoodie",
//   "I need a pair of breathable jogging pants",
//   "Find me a light summer cardigan",
//   "I want to buy a pair of cuffed denim shorts",
//   "Show me soft leather gloves",
//   "Looking for a stylish winter parka",
//   "I need a pair of slim-fit dress pants",
//   "Find me a boho-chic shawl",
//   "I want to buy a pair of combat boots",
//   "Show me funky patterned socks",
//   "Looking for a versatile travel jacket",
//   "I need a pair of warm fleece leggings",
//   "Find me a trendy oversized tee",
//   "I want to buy a pair of luxury cufflinks",
//   "Show me a modern knitted beanie",
//   "Looking for chic eco-friendly sunglasses",
//   "I need a pair of embroidered denim",
//   "Find me a tailored pencil skirt",
//   "I want to buy a stylish cocktail blazer",
//   "Show me a playful polka dot dress",
//   "Looking for a functional gym bag",
//   "I need a pair of stretchable leggings",
//   "Find me a cool retro bomber",
//   "I want to buy a minimalist backpack",
//   "Show me a versatile wrap cardigan",
//   "Looking for a bold printed scarf",
//   "I need a pair of comfy slip-on shoes",
//   "Find me a fashionable trench coat",
//   "I want to buy a pair of high-top sneakers",
//   "Show me vintage band t-shirts",
//   "Looking for a classic leather wallet",
//   "I need a pair of trendy culottes",
//   "Find me a modern athleisure dress",
//   "I want to buy a sleek wristwatch",
//   "Show me comfortable lounge pants",
//   "Looking for a chic swimsuit",
//   "I need a pair of flared trousers",
//   "Find me an elegant silk blouse",
//   "I want to buy a structured blazer",
//   "Show me bohemian embroidered tops",
//   "Looking for functional outdoor jackets",
//   "I need a pair of casual boat shoes",
//   "Find me a unique geometric necklace",
//   "I want to buy a sporty windbreaker",
//   "Show me eco-chic sandals",
//   "Looking for a set of minimalist rings",
//   "I need a pair of comfortable office shoes",
//   "Find me a trendy statement belt",
//   "I want to buy a relaxed-fit turtleneck",
//   "Show me a boho floral kimono",
//   "Looking for a vintage style beret",
//   "I need a pair of stylish bike shorts",
//   "Find me a modern asymmetric dress",
//   "I want to buy a lightweight track jacket",
//   "Show me a minimalist graphic sweatshirt",
//   "Looking for a pair of retro sneakers",
//   "I need a bold color block sweater",
//   "Find me a versatile shawl collar coat",
//   "I want to buy a pair of chic ankle boots",
//   "Show me a trendy sequin top",
//   "Looking for an elegant lace dress",
//   "I need a pair of comfy satin pajamas",
//   "Find me a stylish crossbody bag",
//   "I want to buy a set of designer cuff bracelets",
//   "Show me a relaxed-fit denim shirt",
//   "Looking for a vibrant tie-dye hoodie",
//   "I need a pair of breathable mesh sneakers",
//   "Find me a sleek modern blazer",
//   "I want to buy a unique statement ring",
//   "Show me a refined leather jacket",
//   "Looking for a classic crew neck sweater",
//   "I need a pair of durable work boots",
//   "Find me a pair of casual sneakers for walking",
//   "I want to buy a pair of fitted jeans",
//   "Show me a timeless pearl necklace",
//   "Looking for a sporty polo shirt",
//   "I need a pair of performance athletic shorts",
//   "Find me a soft cashmere cardigan",
//   "I want to buy a vibrant summer tunic",
//   "Show me a pair of classic ballet flats",
//   "Looking for a chic minimalist cap",
//   "I need a pair of trendy sports sneakers",
//   "Find me a modern layered pendant",
//   "I want to buy a bohemian fringe bag",
//   "Show me a stylish printed kimono",
//   "Looking for a unique patchwork jacket",
//   "I need a pair of comfortable office flats",
//   "Find me a sleek monochrome outfit",
//   "I want to buy a modern pleated blouse",
//   "Show me a colorful beaded bracelet",
//   "Looking for a pair of edgy platform shoes",
//   "I need a lightweight summer skirt",
//   "Find me a chic minimalist wallet",
//   "I want to buy a set of vintage-inspired earrings",
//   "Show me a modern, edgy trench",
//   "Looking for a pair of comfortable espadrilles",
//   "I need a vibrant printed maxi skirt",
//   "Find me a stylish reversible jacket",
//   "I want to buy a unique boho necklace",
//   "Show me a pair of sleek racing sneakers",
//   "Looking for a classic ribbed sweater",
//   "I need a pair of breathable running shoes",
//   "Find me a modern asymmetrical top",
//   "I want to buy a pair of summer culottes",
//   "Show me a trendy oversized blazer",
//   "Looking for a pair of slim athletic pants",
//   "I need a sophisticated wool coat",
//   "Find me a chic off-shoulder dress",
//   "I want to buy a pair of eco-friendly flip flops",
//   "Show me a comfortable gym outfit",
//   "Looking for a stylish printed bomber",
//   "I need a pair of smart casual sneakers",
//   "Find me a trendy lace-up boot",
//   "I want to buy a set of matching accessory pieces",
//   "Show me a modern abstract print dress",
//   "Looking for a unique asymmetrical skirt",
//   "I need a pair of cozy knit beanies",
//   "Find me a functional sports jacket",
//   "I want to buy a pair of rugged hiking shoes",
//   "Show me a trendy varsity jacket",
//   "Looking for a timeless A-line dress",
//   "I need a pair of retro running shoes",
//   "Find me a modern draped top",
//   "I want to buy a pair of casual moccasins",
//   "Show me a chic minimalist ring set",
//   "Looking for a pair of comfortable flats for walking",
//   "I need a lightweight, packable jacket",
//   "Find me a trendy floral bomber",
//   "I want to buy a pair of statement sneakers",
//   "Show me a stylish monochrome scarf",
//   "Looking for a versatile dress for work",
//   "I need a pair of functional sports caps",
//   "Find me a modern, relaxed-fit blouse",
//   "I want to buy a pair of elegant satin pumps",
//   "Show me a boho-inspired fringe jacket",
//   "Looking for a pair of sporty waterproof shoes",
//   "I need a chic wool beret",
//   "Find me a trendy sports polo",
//   "I want to buy a unique handwoven bag",
//   "Show me a modern cut-out dress",
//   "Looking for a pair of durable trail shoes",
//   "I need a vibrant graphic print sweatshirt",
//   "Find me a stylish, reversible scarf",
//   "I want to buy a pair of relaxed-fit denim pants",
//   "Show me a modern mock neck top",
//   "Looking for a pair of bold, printed leggings",
//   "I need a comfortable pair of casual sandals",
//   "Find me a modern, minimalist watch",
//   "I want to buy a pair of statement athletic shoes",
//   "Show me a trendy tie-front top",
//   "Looking for a chic, flared midi skirt",
//   "I need a pair of breathable summer sneakers",
//   "Find me a stylish quilted jacket",
//   "I want to buy a pair of classic sailor shoes",
//   "Show me a unique embroidered vest",
//   "Looking for a sleek leather bomber",
//   "I need a pair of elegant embroidered flats",
//   "Find me a modern sports smartwatch",
//   "I want to buy a statement fedora hat",
//   "Show me a chic ruched maxi dress",
//   "Looking for a versatile stretch denim jacket",
//   "I need a pair of stylish tulle skirts",
//   "Find me a comfortable pair of slip-on loafers",
//   "I want to buy a vibrant patterned tunic",
//   "Show me a trendy oversized denim shirt",
//   "Looking for a bold, colorful windbreaker",
//   "I need a pair of classic, slim-fit trousers",
//   "Find me a stylish, vintage cardigan",
//   "I want to buy a unique geometric print top",
//   "Show me a chic faux fur jacket",
//   "Looking for a pair of elegant satin shorts",
//   "I need a pair of durable trail running shoes",
//   "Find me a modern, cropped sweater",
//   "I want to buy a pair of slim-fit joggers",
//   "Show me a trendy bow detail top",
//   "Looking for a stylish floral print blouse",
//   "I need a pair of warm, knitted mittens",
//   "Find me a versatile utility vest",
//   "I want to buy a pair of high-waisted trousers",
//   "Show me a chic minimalist bucket hat",
//   "Looking for a pair of retro cuffed jeans",
//   "I need a modern oversized graphic tee",
//   "Find me a classic patterned scarf",
//   "I want to buy a pair of cozy, fleece-lined leggings",
//   "Show me a trendy color-block hoodie",
//   "Looking for a stylish t-shirt dress",
//   "I need a pair of breathable gym sneakers",
//   "Find me a modern, relaxed-fit denim jacket",
//   "I want to buy a pair of athletic compression shorts",
//   "Show me a chic velvet blazer",
//   "Looking for a pair of casual, embroidered sneakers",
//   "I need a pair of classic chinos",
//   "Find me a trendy wrap-front dress",
//   "I want to buy a pair of durable canvas shoes",
//   "Show me a stylish, high-neck sweater",
//   "Looking for a pair of comfy running tights",
//   "I need a modern, sleek windbreaker",
//   "Find me a vibrant, printed kimono",
//   "I want to buy a pair of eco-friendly sneakers",
//   "Show me a trendy metallic top",
//   "Looking for a pair of casual tailored shorts",
//   "I need a pair of minimalist, unisex sneakers",
//   "Find me a modern asymmetrical blazer",
//   "I want to buy a pair of loose-fit linen pants",
//   "Show me a stylish leopard print jacket",
//   "Looking for a pair of elegant high-heeled boots",
//   "I need a trendy sporty tracksuit",
//   "Find me a modern graphic baseball cap",
//   "I want to buy a pair of comfortable ballet flats",
//   "Show me a unique artistic print skirt",
//   "Looking for a pair of slim-fit overalls",
//   "I need a modern structured denim vest",
//   "Find me a chic pastel-colored sweater",
//   "I want to buy a pair of stylish, high-waisted shorts",
//   "Show me a trendy varsity sweatshirt",
//   "Looking for a pair of classic double-breasted blazers",
//   "I need a comfortable pair of casual clogs",
//   "Find me a modern, cropped denim jacket",
//   "I want to buy a pair of high-quality hiking boots",
//   "Show me a trendy, fitted polo shirt",
//   "Looking for a pair of bohemian fringe boots",
//   "I need a pair of sleek, minimalist ankle boots",
//   "Find me a modern, striped crew neck tee",
//   "I want to buy a pair of eco-friendly cargo pants",
//   "Show me a stylish, fitted blazer",
//   "Looking for a pair of comfortable, vintage sneakers",
//   "I need a pair of cozy, oversized sweaters",
//   "Find me a chic, leather crossbody bag",
//   "I want to buy a pair of smart, tailored trousers",
//   "Show me a trendy, statement graphic tee",
//   "Looking for a pair of sleek, reflective running shoes",
//   "I need a modern, minimalist cap",
//   "Find me a stylish, patterned tote bag",
//   "I want to buy a pair of high-performance gym shoes",
//   "Show me a chic, embroidered denim skirt",
//   "Looking for a pair of comfortable, stylish moccasins",
//   "I need a pair of warm, water-resistant boots",
//   "Find me a trendy, asymmetrical sweater",
//   "I want to buy a pair of unique, embroidered joggers",
//   "Show me a stylish, casual slip-on sneaker",
//   "Looking for a pair of high-end athletic leggings",
//   "I need a modern, versatile leather jacket",
//   "Find me a chic, relaxed-fit trench coat",
//   "I want to buy a pair of trendy, casual sandals",
//   "Show me a unique, abstract print top",
//   "Looking for a pair of classic, tapered jeans",
//   "I need a pair of comfortable, vintage boots",
//   "Find me a modern, streamlined hoodie",
//   "I want to buy a pair of bold, patterned trousers",
//   "Show me a chic, high-waisted pencil skirt",
//   "Looking for a pair of modern, sleek dress shoes",
//   "I need a pair of sporty, comfortable slip-ons",
//   "Find me a stylish, relaxed-fit sweater",
//   "I want to buy a pair of functional, rugged cargo shorts",
//   "Show me a trendy, boxy denim jacket",
//   "Looking for a pair of elegant, fitted capris",
//   "I need a pair of minimalist, breathable running shoes",
//   "Find me a modern, versatile pullover hoodie",
//   "I want to buy a pair of unique, edgy cuffed pants",
//   "Show me a stylish, classic rugby shirt",
//   "Looking for a pair of vibrant, patterned joggers",
//   "I need a pair of modern, slim-fit suit pants",
//   "Find me a trendy, embroidered bomber jacket",
//   "I want to buy a pair of comfortable, breathable loafers",
//   "Show me a chic, minimalist ankle boot",
//   "Looking for a pair of stylish, low-top sneakers",
//   "I need a pair of durable, waterproof trail boots",
//   "Find me a modern, fitted turtleneck sweater",
//   "I want to buy a pair of trendy, casual loafers",
//   "Show me a unique, retro-inspired windbreaker",
//   "Looking for a pair of stylish, comfortable culottes",
//   "I need a pair of modern, versatile athletic shorts",
//   "Find me a chic, minimalist crew neck sweatshirt",
//   "I want to buy a pair of eco-friendly, breathable sneakers",
//   "Show me a stylish, modern scarf",
//   "Looking for a pair of comfortable, slim-fit joggers",
//   "I need a pair of trendy, double-breasted blazers",
//   "Find me a modern, edgy hoodie",
//   "I want to buy a pair of unique, patterned boat shoes",
//   "Show me a stylish, cropped sweater",
//   "Looking for a pair of classic, unisex sneakers",
//   "I need a pair of breathable, lightweight running shorts",
//   "Find me a modern, minimalist track jacket",
//   "I want to buy a pair of comfortable, durable trainers",
// ];


// Define templates with placeholders represented by {}
const templates = [
  "I'm looking for a {} {} for {}.",
  "Can someone recommend a {} {}?",
  "I need a {} {} for {}.",
  "Where can I find a {} {} that is {}?",
  "Show me some {} {} for {}.",
  "I want a {} {} for {}.",
  "Help me find a {} {} that is {}.",
  "I'm after a {} {} for {}.",
  "Looking for a {} {} that fits {}.",
  "I want to buy a {} {} for {}."
];

// Lists of adjectives, items, and contexts
const adjectives = [
  "cozy", "stylish", "comfortable", "durable", "elegant", "trendy", "modern",
  "vintage", "casual", "sophisticated", "minimalist", "unique", "bold", "colorful",
  "chic", "versatile", "soft", "snug", "relaxed", "edgy", "refined", "cool",
  "fresh", "innovative", "classic"
];

const items = [
  "sweater", "raincoat", "sneakers", "jacket", "dress", "boots", "bag", "tee",
  "jeans", "blazer", "belt", "hat", "shirt", "hoodie", "shorts", "trousers",
  "skirt", "cap", "gloves", "scarf", "watch", "suit", "leggings", "cardigan",
  "overalls", "maxi dress", "polo shirt", "sunglasses", "ankle boots", "denim jacket",
  "vest", "sweatpants", "t-shirt", "puffer jacket", "culottes", "romper", "kimono",
  "tank top", "joggers", "pajamas", "turtleneck", "tracksuit", "espadrilles"
];

const contexts = [
  "winter", "summer", "for a party", "for work", "for travel", "for everyday use",
  "for a wedding", "for a casual day out", "for outdoor activities", "for a workout",
  "for a special occasion", "for running", "for lounging", "for an event", "for a date",
  "for a festival", "for a night out", "for hiking", "for the beach", "for a trip",
  "in the city", "for a business meeting", "for exercise", "for a relaxed weekend"
];

// Utility function to get a random element from an array
function getRandomElement(arr:any) {
  return arr[Math.floor(Math.random() * arr.length)];
}

// Function to fill in placeholders in a template string.
// It replaces each '{}' in the template sequentially with the provided values.
function fillTemplate(template:any, ...values:any) {
  let i = 0;
  return template.replace(/{}/g, () => values[i++]);
}

// Generate 500 human-like queries
const humanQueries = [];
const totalQueries = 500;

for (let i = 0; i < totalQueries; i++) {
  const template = getRandomElement(templates);
  const adj1 = getRandomElement(adjectives);
  const item = getRandomElement(items);
  const context = getRandomElement(contexts);
  const adj2 = getRandomElement(adjectives);

  // Count placeholders in the template to determine if we need three or four values
  const placeholderCount = (template.match(/{}/g) || []).length;

  let query = "";
  if (placeholderCount === 3) {
    query = fillTemplate(template, adj1, item, context);
  } else if (placeholderCount === 4) {
    query = fillTemplate(template, adj1, item, context, adj2);
  } else {
    // Fallback if unexpected, defaulting to three placeholders
    query = fillTemplate(template, adj1, item, context);
  }
  
  humanQueries.push(query);
}

// Log the first 10 queries to verify
console.log(humanQueries.slice(0, 10));

// Optionally, log the complete list
// console.log(humanQueries);


Promise.all(
  humanQueries.map(async (query) => {
    await prisma.UserQuery.create({
      data: {
        queryText: query,
      },
    });
    console.log("Query done: ", query);
  })
)
  .then(() => {
    console.log("All queries processed");
    prisma.$disconnect();
  })
  .catch((e) => {
    console.error(e);
    prisma.$disconnect();
  });
