import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { getServerSession } from "next-auth";
import { Header } from "@/components/landing/header";

import { authOptions } from "@/lib/auth";
import { Toaster } from "@/components/ui/sonner";
import { HistoryDrawer } from "@/components/sidebar/HistoryDrawer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <head></head>
      <Providers session={session}>
        <body className={`${inter.className} font-serif`}>
          <Header />
          {children}
          <HistoryDrawer />
        </body>
        <Toaster />
      </Providers>
    </html>
  );
}
